defaults: &defaults
  title: "萝卜停车"
  description: "萝卜停车"
  keywords: "萝卜停车"
  host: "萝卜停车"
  site_name: "lbpark"
  spider_interval: 5 * 60
  spider_usd_rmb_interval: 5 * 60
  default_email_sender: "notification@lbpark.com"
  amap_key: "32cc52a3dc04fc771382778dc5cc50e9"
  park_status_duration: 3600
  lottery_ratio: 75
  park_info_encrypted: true
  production: true
  qr_code_url: 'http://qrcode.6luobo.com'
  four_zero_zero: "4008-117-927"
  coupons_visible_range: 10000
  parks_visible_range: 1000


development:
  <<: *defaults
  spider_interval: 10
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  production: true

demo:
  <<: *defaults
