defaults: &defaults
  title: "萝卜停车"
  description: "萝卜停车"
  keywords: "萝卜停车"
  host: "萝卜停车"
  site_name: "lbpark"
  spider_interval: 5 * 60
  spider_usd_rmb_interval: 5 * 60
  default_email_sender: "notification@lbpark.com"
  amap_key: "32cc52a3dc04fc771382778dc5cc50e9"
  park_status_duration: 30 * 60
  lottery_ratio: 40
  park_info_encrypted: true
  production: false


development:
  <<: *defaults
  spider_interval: 10
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  production: true

demo:
  <<: *defaults
