button:
  -
    type: "view"
    name: "找车位"
    url: "http://m.6luobo.com"
  -
    type: "view"
    name: "提前搜"
    url: "http://m.6luobo.com/mobile/hot_place"
  -
    type: "view"
    name: "我的"
    url: "http://m.6luobo.com/mobile/setting"
