button:
  -
    type: "view"
    name: "找车位"
    url: "http://6luobo.com"
  -
    type: "view"
    name: "提前搜"
    url: "http://6luobo.com/hot_place"
  -
    type: "view"
    name: "我的"
    url: "http://6luobo.com/setting"
