default: &default

  appid: "wx97b3f3548f2c5c76"
  secret: "d56a540fe90eb8848f440e8ed8b18aa0"
  token:  "thisistoken"

production:
<<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
