default: &default
  appid: "wx74e2705cf0a80df8"
  secret: "7506cf446cb2fa21f7ae0d1b4ae66da4"
  token:  "thisistoken"
  access_token: "/home/ubuntu/wechat_access_token"
  vendor_appid: "wx74e2705cf0a80df8"
  vendor_secret: "7506cf446cb2fa21f7ae0d1b4ae66da4"
  vendor_token:  "thisistoken"
  vendor_access_token: "/home/ubuntu/vendor_wechat_access_token"

production:
  <<: *default

demo:
  <<: *default


staging:
  <<: *default

development:
  <<: *default
  access_token: "/Users/cmingxu/wechat_access_token"
  vendor_access_token: "/Users/cmingxu/vendor_wechat_access_token"

test:
  <<: *default
