default: &default
  appid: "wx74e2705cf0a80df8"
  secret: "7506cf446cb2fa21f7ae0d1b4ae66da4"
  token:  "thisistoken"

production:
<<: *default

demo:
<<: *default


staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
